services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: laravel12-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: inventory_management_system
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_CLIENT: phpredis
      REDIS_URL: redis://:password@host.docker.internal:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel

  web:
    image: nginx:1.25-alpine
    container_name: laravel12-nginx
    restart: unless-stopped
    ports:
      - "7152:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
