version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: laravel12-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount code for live edit; if you want pure prod, remove this line.
      - ./:/var/www/html
      # Keep vendor cached on host so builds are faster; optional in prod.
      - ./vendor:/var/www/html/vendor:cached
      # Ensure storage is writable and persistent
      - ./storage:/var/www/html/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: [laravel]

  web:
    image: nginx:1.25-alpine
    container_name: laravel12-nginx
    restart: unless-stopped
    ports:
      - "7152:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks: [laravel]

networks:
  laravel:
    driver: bridge
