services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: mylaravel-php81
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./vendor:/var/www/html/vendor
            - ./storage:/var/www/html/storage
        env_file:
            - .env
        # allow containers to reach services running on the host
        extra_hosts:
            - "host.docker.internal:host-gateway"
            # On Linux this maps host.docker.internal → your host IP
        networks: [laravel]

    web:
        image: nginx:1.25-alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: [app]
        networks: [laravel]

networks:
    laravel:
        driver: bridge
